### ISSUE TITLE
Error opening file for reading; filename='/proc/kmsg', error='Operation not permitted (1)'

### ISSUE THREAD

**Issue by xytian315** [balabit/syslog-ng-docker#35]
$ docker run -it -p 514:514 -p 601:601 --name syslog-ng balabit/syslog-ng:latest --no-caps
[2018-10-16T22:24:43.054450] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
[2018-10-16T22:24:43.054957] Error opening file for reading; filename='/proc/kmsg', error='Operation not permitted (1)'
[2018-10-16T22:24:43.055000] Error initializing message pipeline; plugin_name='file', location='source generator system:10:1'

$ docker --version
Docker version 18.06.1-ce, build e68fc7a

**Comment by szemere** [comment]
Dear @xytian315,
 Thank you for reporting this issue. Unfortunatelly I forgot to modify the Dockerfile according to the mentioned change in syslog-ng.
 I hope the PR will fix your issue, but if you share your usecase, we will investigate it properly. (i.e.: Do you need to read `/proc/kmsg`, because in that case the default run command will not suitable for you. We can help in this case too.)

Br,
Laci

**Comment by mitzkia** [comment]
Sorry, it was close accidentally. 
Of course we will wait for your answer @xytian315 related to this issue.

**Comment by xytian315** [comment]
Hi, guys, thank you so much for fixing this issue so quickly. I have tried the new deployment. It works! 👍
