### ISSUE TITLE
$HOST is the Docker Root IP on MacOS

### ISSUE THREAD

**Issue by drexlma** [balabit/syslog-ng-docker#44]
i dont know why

**Comment by szemere** [comment]
Dear @drexlma ,
 please share some details.

Laci

**Comment by drexlma** [comment]
server: 
`@version: 3.9
 
source s_net {
   tcp(
     ip("0.0.0.0")
   );
   syslog(
     ip("0.0.0.0")
   );
 };

destination d_mysql {
	sql(
		type(mysql)
		username("syslog")
		password("xxx")
		database("syslog")
		host("10.60.0.99")
		table("logs")
		columns("host", "facility", "priority", "level", "tag", "datetime", "program", "msg")
		values("$HOST", "$FACILITY", "$PRIORITY", "$LEVEL", "$TAG","$YEAR-$MONTH-$DAY $HOUR:$MIN:$SEC","$PROGRAM", "$MSG")
		indexes("datetime", "host", "program", "pid", "message")
	);
};

destination d_file {
	file("/var/log/syslog");
};

log {
	source(s_net); 
	destination(d_file);
	destination(d_mysql);
};
 `

client: 
`cat /etc/syslog-ng/conf.d/se.conf
log {
	source(s_src);
	destination(d_remote);
};

destination d_remote {
	tcp("192.168.178.48" port(514));
};
`


tail syslog
Jun 18 14:04:53 172.19.0.1 drexlmaier: System rebooted for hard disk upgrade


composerfile
`
  syslog:
          hostname:   syslog.php.rz1.dbe.academy
          build:
                  context: ./dockerfiles/
                  dockerfile: Dockerfile.syslog
          networks:
                dev:
                        ipv4_address: 172.19.0.6
          ports:
                  - "514:514"
                  - "601:601"
                  - "6514:6514"
          container_name: syslog
          restart: "no"
          volumes:
                  - ./syslog-ng/conf/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
 networks:
  dev:
          driver: bridge
          ipam:
                  config:
                          - subnet: 172.19.0.0/24`

**Comment by szemere** [comment]
Hello,
 thank you for attaching the compose file too.

 The behavior is coming from the limitation of the docker environment. If one is using bridged networking, the application inside the docker container do not get the remote IP address at all. (Just some results from a quick Google search as a reference: https://github.com/docker/for-linux/issues/182 , https://github.com/moby/moby/issues/15086 , https://forums.docker.com/t/nginx-cannot-get-to-client-ip/52602/3)

 You can test this by starting a netcat "server" inside a container. With the -v (verbose) option it will print remote ip addresses in case of incoming connections.

 As far as I can see, most of the people get rid of this problem by using `host` network mode instead of bridge networking. Of course it has some security implications and usually not recommended in production environments.
 A rare solution I come across is to use some low level proxy on the host machine to forward and annotate packets for the applications.

Br,
Laci

**Comment by szemere** [comment]
Dear @drexlma,
 I will close this ticket due to inactivity. Please feel free to reopen it if needed.

 A final note from my point: I focused so much on the server issue, I haven't noticed that your client is also a syslog-ng instance. As a workaround to this docker limitation, you can pack the client IP information into the log message with syslog-ng itself (i.e.: into the SDATA field), so there is no need for any proxy or network configuration change.

Br,
Laci

**Comment by drexlma** [comment]
> Hello,
> thank you for attaching the compose file too.
> 
> The behavior is coming from the limitation of the docker environment. If one is using bridged networking, the application inside the docker container do not get the remote IP address at all. (Just some results from a quick Google search as a reference: [docker/for-linux#182](https://github.com/docker/for-linux/issues/182) , [moby/moby#15086](https://github.com/moby/moby/issues/15086) , https://forums.docker.com/t/nginx-cannot-get-to-client-ip/52602/3)
> 
> You can test this by starting a netcat "server" inside a container. With the -v (verbose) option it will print remote ip addresses in case of incoming connections.
> 
> As far as I can see, most of the people get rid of this problem by using `host` network mode instead of bridge networking. Of course it has some security implications and usually not recommended in production environments.
> A rare solution I come across is to use some low level proxy on the host machine to forward and annotate packets for the applications.
> 
> Br,
> Laci

None of it helps. Thanks anyway.

I'm now installing Docker in a Virtuelbox.

**Comment by drexlma** [comment]
after long time... i install debian 10 on Virtualbox on MacOs... with docker
