### ISSUE TITLE
Reload syslog-ng in container

### ISSUE THREAD

**Issue by SergeSpinoza** [balabit/syslog-ng-docker#49]
Hi. 
How I can reload syslog-ng in docker? 
When I try to do `docker exec -ti syslog-ng /etc/init.d/syslog-ng reload` I have a error: 

```
[....] Reload system logging: syslog-ngsyslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted'
[2019-12-13T17:14:10.067630] WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.24 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file.;
 failed!
```

It's need when I rotate log files via logrotate on host (in mounted volume in container). 

Thanks.

**Comment by gaborznagy** [comment]
Hi @SergeSpinoza,

I've checked and had the same issue as you have.

It seems, that our init script has a hard-coded pidfile value `/var/run/syslog-ng.pid`, while syslog-ng's pidfile is created elsewhere: `/var/lib/syslog-ng/syslog-ng.pid`

Unti this is fixed, I would recommend to modify the init script, or use `syslog-ng-ctl reload` instead of `service syslog-ng reload` for now.

**Comment by SergeSpinoza** [comment]
Hi @gaborznagy! 

`syslog-ng-ctl reload` - it's works! Thanks!

**Comment by drexlma** [comment]
https://github.com/balabit/syslog-ng-docker/wiki#reload-syslog

close?

**Comment by MrAnno** [comment]
Thanks!
