### ISSUE TITLE
syslog-ng stops relaying messages over udp after "bad lenght"

### ISSUE THREAD

**Issue by fillthecurse** [balabit/syslog-ng-docker#67]
We are relaying messages to external syslog server 2.2.2.2 via udp, and following scenario is observed:

Monitoring with tcpdump we observe the udp traffic, normally the length is between 80-400 bytes. Every now and then we receive big event which syslog-ng tries to relay to remote server 2.2.2.2

IP 1.1.1.1.34944 > 2.2.2.2.514: UDP, bad length 35190 > 1408

At this moment tcpdump logs stop and in syslog-ng log file we see this output:

Nov 26 21:32:53 afa42ca2eec1 syslog-ng[1]: Syslog connection established; fd='19', server='AF_INET(2.2.2.2:514)', local='AF_INET(0.0.0.0:0)'
Nov 26 21:32:53 afa42ca2eec1 syslog-ng[1]: I/O error occurred while writing; fd='19', error='Message too long (90)'
Nov 26 21:32:53 Syslog connection broken; fd='19', server='AF_INET(2.2.2.2:514)', time_reopen='5'

These messages repeat indefinitely every 5 seconds as this is the reopen time, but syslog-ng never tries to send again to that destination.
syslog-ng now is completely hanging and not trying to send anything to destination 2.2.2.2, but it is sending fine to other destinations. The only fix for destination 2.2.2.2 is restart of the whole container. 

config is:

#############################################################################
# Default syslog-ng.conf file which collects all local logs into a
# single file called /var/log/messages.
#

@version: 3.29
@include "scl.conf"

################################################################################
################################################################################

options { chain_hostnames(off);
        time_reopen (5);
        flush_lines(0);
        group(41812);
        dir_group(41812);
        dir_perm(0770);
        perm(0660);
        use_dns(persist_only);
        dns_cache_hosts(/etc/hosts);
        threaded(yes);
        log_fifo_size(200000);
};

source s_internal {
        internal();
};

source s_network {
        tcp(max-connections(500) log_iw_size(11000));
        udp( so_rcvbuf(67108864) so_sndbuf(67108864));
};

destination X {
        udp("2.2.2.2" port("514") );
};

log {
        source(s_network);  destination(X);
};

**Comment by bazsi** [comment]
Hmmm, udp should support datagram sizes up to ~64kb, in the worst case the
datagram would become fragmented.

In any case you can control the maximum message size using log-msg-size()
which would cause the input message to be split into to.

Or there was a recent addition to syslog-ng to truncate the udp datagram
just before sending out (something like truncate-len() option for the udp
destination, but I can't remember the exact name, checks the release
announcement for 3.30)

**Comment by fillthecurse** [comment]
Thanks for your feedback bazsi,

We are using latest docker image which is based on 3.29. We are using default log-msg-size() and there are no issues with it. The source that sends those sporadic huge events is sending via tcp, so also no issues there. But the relaying part where syslog-ng now needs to send this event over udp to another remote host fails. I am ok if syslog-ng decides to drop this even due to its size, but not to completely hang and make the destination unusable anymore until I restart it.

I guess I need to wait for the image to be updated with 3.30 and then test truncate_size()

**Comment by szemere** [comment]
Hello @fillthecurse,

 I also tested your setup. I think Bazsi explained everything correctly, just a little clarification:

- log-msg-size() controls the maximum message size Syslog-ng can receive. (We calculate buffer sizes from that value, and helps the parsers to avoid buffer overflow scenarios.)
- You mentioned that you will be fine dropping the oversized messages. "Unfortunately" Syslog-ng rather not do that, that's why the infinite loop. Kokan recognized and fixed this in: https://github.com/syslog-ng/syslog-ng/pull/3474 With the ability to truncate outgoing messages. So the option which @bazsi mentionied is "truncate-size()"
- Unfortunately the syslog-ng-docker image is still updated manually (we are working on the automation), so there could be some delay between the official Syslog-ng release and the new Docker image. The 3.30.1 is now available at dockerhub: https://hub.docker.com/repository/registry-1.docker.io/balabit/syslog-ng/builds/14500b08-8cc2-459c-96f9-c6ec205413b3
- Maybe you are referring to an internal update, rather than DockerHub. In this case as a temporary workaround you can use the "substr" template function to truncate your messages. But I really not recommend this as a long term solution since it do not care about the overall message size (just the generated part), so this setup will be very fragile.

Br,
Laci

**Comment by fillthecurse** [comment]
Thank you, Laszlo, for this update.

I think it is clear to me now how this works and what I need to perform in terms of configuration and testing.

Thank you both again for the quick and helpful feedbacks.
